name: CICD

on:
 workflow_dispatch:
  inputs:
   env:
    description: choose the environment
    default: 'dev'
    required: true
    type: choice
    options:
     - prod
     - dev
     - Uat

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: build the code
     run: echo "code is build"
 test:
  needs: [build]
  runs-on: ubuntu-latest
  steps:
   - name: test the code
     run: echo "code is tested"
 deploy:
  if: inputs.env == 'dev'
  needs: [build,test]
  runs-on: ubuntu-latest
  steps:
   - name: deploy the code
     run: echo "code is deployed"
     
     

     
    
 
