name: hello

on:
 push:
  branches: [main]

jobs:
 greet:
  runs-on: ubuntu-latest
  steps:
    - name: say hello to users
      run: echo "hello"

    - name: say hello to usernames
      run: echo "hello $USER"

 details:
  runs-on: ubuntu-latest
  steps:
   - name: publish details of docker and pyhton version
     run: docker --version && python --version
      
     
